kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: observability-cluster
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings: # Port forward on the host to node
    - containerPort: 80
      hostPort: 80
      protocol: TCP
    # Note: use 443 for TLS
    # - containerPort: 443
    #   hostPort: 443
    #   protocol: TCP
  - role: worker
